version: '3.1'

services:
  chillis-restaurant-backend:
    image: chillsrestaurant-app:latest
    ports:
      - "8081:8081"
    environment:
        - SERVER_PORT=8081
        - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/chillisdb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=rootroot
        - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_JPA_SHOW_SQL=true
        - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
        - SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=INFO
        - LOGGING_LEVEL_COM_chillsrestaurant=DEBUG
        - SPRING_DEVTOOLS_RESTART_ENABLED=true
        - TOKEN_SIGNING_KEY=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
        - SERVER_SSL_KEY-STORE=file:/src/main/resources/keystore.p12
        - SERVER_SSL_KEY-STORE-PASSWORD=Cjmv1329!
        - SERVER_SSL_KEY-STORE-TYPE=PKCS12
        - SERVER_SSL_KEY-ALIAS=tomcat
    networks:
      app-network:
        ipv4_address: 172.20.1.10

  mariadb:
    image: yobasystems/alpine-mariadb:arm32v7
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=chillisdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      app-network:
        ipv4_address: 172.20.1.11

  react-app:
    image: chills-app:latest
    ports:
      - "8082:8082"
    environment:
      - REACT_APP_API_URL=https://172.20.1.10:8081
    restart: unless-stopped
    networks:
      app-network:
        ipv4_address: 172.20.1.12

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - /home/cmoreno/Docker_Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/cmoreno/Docker_Nginx:/etc/nginx/certs:ro
    networks:
      app-network:

volumes:
  mariadb-data:

networks:
  app-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.1.0/16
