version: '3.1'

services:
  chillis-restaurant-backend:
    image: chillisrestaurant-app:latest
    ports:
      - "8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/chillisdb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
      # Remaining environment variables...
    depends_on:
      - mariadb
    networks:
      - default

  mariadb:
    image: yobasystems/alpine-mariadb:arm32v7
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=chillisdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - default

  react-app:
    image: chills-app:latest
    ports:
      - "8082:8082" # Here we expose the container's port 80 to host's port 8082
    environment:
      - REACT_APP_API_URL=http://chillis-restaurant-backend:8081 # Backend service URL
    restart: unless-stopped
    depends_on:
      - chillis-restaurant-backend
    networks:
      - default

volumes:
  mariadb-data:

networks:
  default:
