version: "3.1"

services:
  chillis-restaurant-backend:
    image: chillisrestaurant-app:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/chillisdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootroot
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TOKEN_SIGNING_KEY=413F4428472B4B6250655368566D5970337336763979244226452948404D6351